### ISSUE TITLE
Fails to load

### ISSUE THREAD

**Issue by aurel-g** [windfancy/zsq_prompt#3]
Hi, I got this error when trying to load ComfyUI:

```
Launching ComfyUI from: /mnt/comfyui/app

Total VRAM 16073 MB, total RAM 32000 MB
pytorch version: 2.5.1+cu124
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 4060 Ti : cudaMallocAsync
Using pytorch cross attention
[Prompt Server] web root: /mnt/comfyui/app/web
Traceback (most recent call last):
  File "/mnt/comfyui/app/nodes.py", line 2035, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/mnt/comfyui/app/custom_nodes/zsq_prompt/__init__.py", line 1, in <module>
    from .zsq_prompt import PortraitStyler
  File "/mnt/comfyui/app/custom_nodes/zsq_prompt/zsq_prompt.py", line 6, in <module>
    from .config import SCRIPT_DIR,PROMPT_STYLES_DIR,FOOOCUS_STYLES_DIR,RESOURCES_DIR
ImportError: cannot import name 'FOOOCUS_STYLES_DIR' from 'zsq_prompt.config' (/mnt/comfyui/app/custom_nodes/zsq_prompt/config.py)

Cannot import /mnt/comfyui/app/custom_nodes/zsq_prompt module for custom nodes: cannot import name 'FOOOCUS_STYLES_DIR' from 'zsq_prompt.config' (/mnt/comfyui/app/custom_nodes/zsq_prompt/config.py)

Import times for custom nodes:
   0.0 seconds: /mnt/comfyui/app/custom_nodes/websocket_image_save.py
   0.0 seconds (IMPORT FAILED): /mnt/comfyui/app/custom_nodes/zsq_prompt

Starting server

To see the GUI go to: http://0.0.0.0:8080
```

**Comment by aurel-g** [comment]
My bad, I was not up to date :)
